# Generated by Django 5.1.1 on 2024-10-02 04:45

from django.db import migrations  

def populate_role(apps, schemaeditor):
    entries = {
        "developer": "The person who works on issues",
        "scrum master": "The team's coach",
        "product owner": "Responsible for issue creation"
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "the A team",
        "bravo": "The B team",
        "charlie": "The C team"
    }
    Team = apps.get.model("accounts", "Team")
    for key, value in entries.items():
            team_obj = Team(name=key, description=value)
            team_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]
